config/routes.rb
Rails.application.routes.draw do
  
	devise_for :users
	resources:users, only: [:update, :show]
  resources:monsters
	
  authenticated do
    root to: "users#show", as: :authenticated
  end
  
	root to: 'welcome#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
 
	def update
		if current_user.update_attributes(user_params)
			flash[:notice] = "User information updated"
			redirect_to edit_user_registration_path
		else
			flash[:error] = "Invalid user information"
			redirect_to edit_user_registration_path
		end
	end
  
  def show

  end
 
	private
 
	def user_params
		params.require(:user).permit(:name)
	end
end

app/views/users/show.html.erb
<br /><br /><br />

<div class="row">
  <div class="col-md-1"></div>
  
  <div class="col-md-4">
    
    <div class="jumbotron text-center">
      <p>this is just some filler text about what the button does... blah blah</p>
      <%= link_to "Monster Maker", new_monster_path, class: 'btn btn-success btn-lg' %>
    </div>
    
  </div>
  
  <div class="col-md-1"></div>
  
  <div class="col-md-4">
    
    <div class="jumbotron text-center">
      <p>this is just some text about the upcomming character builder... blah</p>
      <%= link_to "Character Builder", root_path, class: 'btn btn-warning btn-lg', disabled: 'disabled' %>
    </div>
    
  </div>
  
</div>